asgardiateam:
  telegram:
    bot:
      token: "5059171928:AAFpfNI9vYvm4dQG7opQ_FgrceK6MovIlf0"
      username: "@housetinchlik_bot"

spring:
  datasource:
    username: postgres
    password: root123
    url: "jdbc:postgresql://localhost:5432/apteka"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

minio:
  bucket-name: "apteka-bot"
  login: "Abdurauf"
  password: "17042004Abdu"
  url: "http://localhost:9000"
